bm-web/src/main/java/fe/tuzla/master/nbp/tracking/TrackingController.java
package fe.tuzla.master.nbp.tracking;

import fe.tuzla.master.nbp.common.DateUtils;
import fe.tuzla.master.nbp.common.TrackingType;
import fe.tuzla.master.nbp.object.TrackingObject;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

@Named
@ViewScoped
public class TrackingController implements Serializable {

    private static TrackingType focusedTracking_ = TrackingType.IN;
    private List<TrackingObject> trackings_;

    @EJB
    private TrackingService trackingService_;

    @PostConstruct
    public void initView() {
        trackings_ = trackingService_.getTrackings();
    }

    public void save(TrackingType trackingType) {
        FacesContext context = FacesContext.getCurrentInstance();
        String message = trackingService_.save(trackingType);
        if (message == null) {
            context.addMessage(
                    null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Successful", "Tracking OK"));
        } else {
            context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN, "Failed", message));
        }
    }

    public void changeFocus(TrackingType type) {
        focusedTracking_ = type;
    }

    public String getTimeDiff(TrackingObject tracking) {
        return DateUtils.getTimeDiffAsStr(tracking.getStartTime(), tracking.getEndTime());
    }

    public String getProductiveHours() {
        List<TrackingObject> temp = new ArrayList<TrackingObject>();
        for (TrackingObject tracking : trackings_) {
            if (tracking.getType() != TrackingType.PAUSE) {
                temp.add(tracking);
            }
        }
        return DateUtils.sumIntervals(temp);
    }

    public TrackingType getFocusedTracking() {
        return focusedTracking_;
    }

    public List<TrackingObject> getTrackings() {
        return trackings_;
    }

    public void setTrackings(List<TrackingObject> trackings) {
        trackings_ = trackings;
    }
}

bm-web/src/main/webapp/modules/mod-tracking/tracking.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                template="/templates/page.xhtml">
    <ui:define name="pageTitle">
        Tracking
    </ui:define>
    <ui:define name="body">
        <p:panelGrid id="trackings" columns="3" layout="grid">
            <p:panelGrid columns="1" styleClass="tracking-panel">
                <f:facet name="header">
                    <p:graphicImage/>
                </f:facet>
                <p:commandLink styleClass="image-section" process="@this"
                               update="trackings"
                               actionListener="#{trackingController.changeFocus('IN')}">
                    <img src="../../resources/images/in.png"/>
                </p:commandLink>
                <h:outputText value="Input"/>
                <p:commandButton rendered="#{trackingController.focusedTracking eq 'IN'}" process="@this"
                                 value="Confirm"
                                 update="table growl"
                                 actionListener="#{trackingController.save('IN')}"/>
            </p:panelGrid>
            <p:panelGrid columns="1" styleClass="tracking-panel">
                <f:facet name="header">
                    <p:graphicImage/>
                </f:facet>
                <p:commandLink styleClass="image-section" process="@this"
                               update="trackings"
                               actionListener="#{trackingController.changeFocus('PAUSE')}">
                    <img src="../../resources/images/pause.jpg"/>
                </p:commandLink>
                <h:outputText value="Pause"/>
                <p:commandButton id="tracking-pause" rendered="#{trackingController.focusedTracking eq 'PAUSE'}"
                                 update="table growl"
                                 value="Confirm" actionListener="#{trackingController.save('PAUSE')}"/>
            </p:panelGrid>
            <p:panelGrid columns="1" styleClass="tracking-panel">
                <f:facet name="header">
                    <p:graphicImage/>
                </f:facet>
                <p:commandLink styleClass="image-section" process="@this"
                               update="trackings"
                               actionListener="#{trackingController.changeFocus('OUT')}">
                    <img src="../../resources/images/out.png"/>
                </p:commandLink>
                <h:outputText value="Output"/>
                <p:commandButton rendered="#{trackingController.focusedTracking eq 'OUT'}" value="Confirm"
                                 update="table growl"
                                 actionListener="#{trackingController.save('OUT')}"/>
            </p:panelGrid>
        </p:panelGrid>
        <!--
        **************************
                Table
        **************************
        -->
        <p:dataTable id="table" styleClass="table" var="tracking" value="#{trackingController.trackings}"
                     widgetVar="table">
            <p:column headerText="Id" style="width: 50px">
                <h:outputText value="#{tracking.id}"/>
            </p:column>

            <p:column headerText="Start time" style="width: 200px;">
                <h:outputText value="#{tracking.startTimeStr}"/>
            </p:column>
            <p:column headerText="End time">
                <h:outputText value="#{tracking.endTimeStr}"/>
            </p:column>
            <p:column headerText="Spent time">
                <h:outputText value="#{trackingController.getTimeDiff(tracking)}"/>
            </p:column>
            <p:column headerText="Type">
                <h:outputText value="#{tracking.type eq 'IN' ? 'Input' : tracking.type eq 'PAUSE' ? 'Pause' : 'Out'}"/>
            </p:column>
            <f:facet name="footer">
                <h:outputText value="Productive hours: #{trackingController.getProductiveHours()}"/>
            </f:facet>
        </p:dataTable>
    </ui:define>
</ui:composition>