bm-web/src/main/java/fe/tuzla/master/nbp/search/SearchController.java
package fe.tuzla.master.nbp.search;

import fe.tuzla.master.nbp.booking.BookingService;
import fe.tuzla.master.nbp.common.SearchParameters;
import fe.tuzla.master.nbp.employee.EmployeeService;
import fe.tuzla.master.nbp.job.JobService;
import fe.tuzla.master.nbp.object.BookingObject;
import fe.tuzla.master.nbp.object.EmployeeObject;
import fe.tuzla.master.nbp.object.JobTypeObject;
import fe.tuzla.master.nbp.object.ProjectObject;
import fe.tuzla.master.nbp.project.ProjectService;
import java.io.Serializable;
import java.sql.Time;
import java.util.Date;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.bean.ViewScoped;
import javax.inject.Named;

@Named
@SessionScoped
public class SearchController implements Serializable {

  private SearchParameters searchParameters_;

  private List<BookingObject> bookings_;

  @EJB private BookingService bookingService_;

  @EJB private EmployeeService employeeService_;

  @EJB private ProjectService projectService_;

  @EJB private JobService jobService_;

  @EJB private SearchService searchService_;

  @PostConstruct
  public void initView() {
//    bookings_ = bookingService_.getBookings();
      searchParameters_ = new SearchParameters();
  }

  public void search(){
    bookings_ = searchService_.search(searchParameters_);
  }

  public List<EmployeeObject> getEmployees() {
    return employeeService_.getAllUsers();
  }

  public List<ProjectObject> getProjects() {
    return projectService_.getAllProjects();
  }

  public List<JobTypeObject> getJobTypes() {
    return jobService_.getAllJobs();
  }

  public Date getDateFromTime(Time time) {
    return new Date(time.getTime());
  }

  public List<BookingObject> getBookings() {
    return bookings_;
  }

  public void setBookings(List<BookingObject> bookings) {
    bookings_ = bookings;
  }

    public SearchParameters getSearchParameters() {
        return searchParameters_;
    }

  public void setSearchParameters(SearchParameters searchParameters) {
    searchParameters_ = searchParameters;
  }
}

bm-web/src/main/webapp/modules/mod-search/search.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                template="/templates/page.xhtml">
    <ui:define name="pageTitle">
        Search
    </ui:define>
    <ui:define name="body">
        <p:panelGrid id="bookings" columns="4" styleClass="search-criteria">
            <p:outputLabel for="popup" value="Date:"/>
            <p:calendar id="popup" pattern="dd.MM.yyyy." value="#{searchController.searchParameters.date}"/>

            <p:outputLabel for="project" value="Project:"/>
            <p:selectOneMenu id="project" value="#{searchController.searchParameters.project}" style="width:80%">
                <f:selectItem itemLabel="Select One"/>
                <f:selectItems value="#{searchController.projects}" var="project"
                               itemLabel="#{project.name}"
                               itemValue="#{project}"/>
                <f:converter binding="#{projectConverter}"/>
            </p:selectOneMenu>

            <p:outputLabel for="jobType" value="Job type:"/>
            <p:selectOneMenu id="jobType" value="#{searchController.searchParameters.jobType}" style="width:80%">
                <f:selectItem itemLabel="Select One"/>
                <f:selectItems value="#{searchController.jobTypes}" var="jobType"
                               itemLabel="#{jobType.name}"
                               itemValue="#{jobType}"/>
                <f:converter binding="#{jobTypeConverter}"/>
            </p:selectOneMenu>

            <p:outputLabel for="employee" value="Employee:"/>
            <p:selectOneMenu id="employee" value="#{searchController.searchParameters.employee}" style="width:80%">
                <f:selectItem itemLabel="Select One"/>
                <f:selectItems value="#{searchController.employees}" var="employee"
                               itemLabel="#{employee.firstName} #{employee.lastName}"
                               itemValue="#{employee}"/>
                <f:converter binding="#{employeeConverter}"/>
            </p:selectOneMenu>

            <p:commandButton value="Search" styleClass="ui-priority-primary"
                             update="table"
                             actionListener="#{searchController.search()}"/>
        </p:panelGrid>
        <!--
          **************************
                  Table
          **************************
          -->
        <p:dataTable id="table" styleClass="table" var="booking" value="#{searchController.bookings}" widgetVar="table">
            <p:column headerText="Id" style="width: 50px">
                <h:outputText value="#{booking.id}"/>
            </p:column>
            <p:column headerText="Date">
                <h:outputText value="#{booking.dateStr}"/>
            </p:column>
            <p:column headerText="Employee" style="width: 100px">
                <h:outputText value="#{booking.employee.firstName} #{booking.employee.lastName}"/>
            </p:column>
            <p:column headerText="Project" style="width: 100px;">
                <h:outputText value="#{booking.project.name}"/>
            </p:column>
            <p:column headerText="Start time">
                <h:outputText value="#{booking.startTimeStr}"/>
            </p:column>
            <p:column headerText="End time">
                <h:outputText value="#{booking.endTimeStr}"/>
            </p:column>
            <p:column headerText="Spent time">
                <h:outputText value="#{bookingController.getTimeDiff(booking)}"/>
            </p:column>
            <p:column headerText="Job type">
                <h:outputText value="#{booking.jobType.name}"/>
            </p:column>
            <p:column headerText="Description" style="width: 200px;">
                <h:outputText value="#{booking.description}"/>
            </p:column>
        </p:dataTable>
    </ui:define>
</ui:composition>